name: Deploy Node.js Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy on EC2
      - name: Deploy app
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/goodtimes || git clone https://github.com/Dharshansr13/aws-cicd.git goodtimes
          cd goodtimes
          git pull origin main
          
          # Build and run Docker
          sudo docker build -t goodtimes-app .
          sudo docker stop goodtimes-app || true
          sudo docker rm goodtimes-app || true
          sudo docker run -d -p 8080:8080 --name goodtimes-app goodtimes-app
          EOF
